apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-api-deployer
  namespace: {{ required "workloadNamespace is required" .Values.workloadNamespace | quote }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: &deploymentVerbs
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs: *deploymentVerbs
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs: *deploymentVerbs
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: *deploymentVerbs
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs: *deploymentVerbs
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vmservicescrapes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-api-deployers
  namespace: {{ required "workloadNamespace is required" .Values.workloadNamespace | quote }}
subjects:
{{- range $group := .Values.workloadDeployerGroups }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ $group | quote }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-api-deployer
