apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-api
  namespace: {{ required "workloadNamespace is required" .Values.workloadNamespace | quote }}
  labels:
    app.kubernetes.io/name: demo-api
    app.kubernetes.io/part-of: nhost-platform-lab
automountServiceAccountToken: false
