apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "workloadNamespace is required" .Values.workloadNamespace | quote }}
  labels:
    app.kubernetes.io/part-of: nhost-platform-lab
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
